function xRange = dbcDbCfgClassificationBase
% DBCDBCFGCLASSIFICATIONBASE creates the basic range of DIVe configuration tags.
% All default values/projects for DIVe classification tag attributes are
% defined here.
% 
% Syntax:
%   xRange = dbcDbCfgClassificationBase
%
% Outputs:
%   xRange - structure with fields: 
%    .systemClass       - cell with strings of valid tags
%    .systemApplication - cell with strings of valid tags
%    .focus             - cell with strings of valid tags
%    .market            - cell with strings of valid tags
%    .performance       - cell with strings of valid tags
%    .project           - cell with strings of valid tags
% 
%
% Example: 
%   xRange = dbcDbCfgClassificationBase
%
% Author: Rainer Frey, TP/EAD, Daimler AG
%  Phone: +49-711-17-34246
% MailTo: rainer.r.frey@daimler.com
%   Date: 2015-08-21

xRange.systemClass = {'Vehicle',...
                      'Bench'};
xRange.systemApplication = {...
                            'Other',...
                            'Powerpack',...
                            'Engine',...
                            'Aftertreatment',...
                            'Cooling',...
                            'Truck',...
                            'BusCoach',...
                            'BusCity',...
                            'Van',...
                            'SpecialVehicle'};
xRange.focus = {'Thermodynamics',...
                'GATS',...
                'CoolingPerformance',...
                'LongitudinalDynamicsEntireVehicleOnRoute',...
                'Other',...
                'SoftwareDevelopment'};
%                 'NVH',...
%                 'Shifting',...
xRange.market = {'EU',...
                 'NAFTA',...
                 'Brazil',...
                 'India',...
                 'Japan',...
                 'China',...
                 'Other',...
                 'RSA',...
                 'UAE',...
                 'KSA',...
                 'NME'};
xRange.performance = {...
                      'fast',...
                      'middle',...
                      'slow',...
                      'unknown'};
%                       'super_fast',...
%                       'very_fast',...
%                       'very_slow',...
xRange.project = {'SFTP','HDEP2020','OBD_stageC'};
return
