% -------------------------------------------------------------------------
% MCM21_MDEG_EURO_10ms_InitFcn.m - generated by Silver T-2022.03-4
% Copyright QTronic GmbH. All rights reserved.
% -------------------------------------------------------------------------

% This m script is loaded when running MCM21_MDEG_EURO_10ms_wrapper.mdl, because in Simulink
%   File/ModelProperties/Callbacks/InitFcn = MCM21_MDEG_EURO_10ms_InitFcn
% Edit this file to change parameter values passed to MCM21_MDEG_EURO_10ms.mexw32

user_config = '-a \\fuelmaps\\EU_MDEG\\X_M1711051_JBN215LF230_LF00_OM936DTC_260kW.dcm -b \\fuelmaps\\EU_MDEG\\X_M1711051_E2P_JBN000LF00_OM936DTC.dcm -c 0.010 -d MVA.csv -e \\loggingfiles\\MeasurementSignals.txt -f 0.1 -g \\initValues\\InitialE2P.txt -h initValues\\InitialE2P.txt -i initValues\\finalE2Ps.txt -W 4 -X 0 -Y TCP -Z 5555'; % user_config options concatenated in one string.
% -a	: parameters to flash; required: yes; default: 0;
% -b	: parameters to flash; required: yes; default: 0;
% -c	: stepSizeDummy; required: yes; default: 0;
% -d	: csv file to write signals; required: yes; default: 0;
% -e	: txt file with regEx for signals to write; required: yes; default: 0;
% -f	: stepSize; required: yes; default: 0;
% -g	: parameters to initialize; required: yes; default: 0;
% -h	: names of E2Ps(measurements) to save after simulation; required: yes; default: 0;
% -i	: target file to save E2Ps after simulation; required: yes; default: 0;
% -W	: log level (default: INFO); required: yes; default: INFO;
% -S	: dynamic sbs file (default: NONE); required: yes; default: 0;
% -D	: macros for dynamic .sbs file (default: NONE); required: yes; default: 0;
% -X	: xcp enabled (default: 0); required: yes; default: off;
% -Y	: xcp protocol (default: TCP); required: yes; default: TCP;
% -Z	: xcp ipPort (default: 5555); required: yes; default: 0;;
