  % example phys.mec.pointmass.generic to automatically generate
  % className and issubspecies entries
  % File in SupportSet "subspecies" with name <species>_subspecies.m contains: 
  cClass = {'aero',{'aero'};...
       'axle',{'axle1','axle2','axle3','axle4','trailerAxle1','trailerAxle2','trailerAxle3'};...
       'brk',{'brk1','brk2','brk3','brk4','trailerBrk1','trailerBrk2','trailerBrk3'};...
       'clt',{'clt'};...
       'eng',{'eng'};...
       'emot',{'emot'};...
       'mass',{'mass'};...
       'mecConsumers',{'mecConsumers'};...
       'ret',{'ret'};...
       'sht',{'shtF','shtR'};...
       'tfc',{'tfc'};...
       'tx',{'tx'};...
       'wheel',{'trailerWheel1','trailerWheel2','trailerWheel3','wheel1','wheel2','wheel3','wheel4'}};
