function [sName] = cpc_cds_name(EEP, CAL)

if isempty(EEP)
    sName = '';
else
    sName = sprintf('CDS_%d_%d_%s_%s_%s_%s_%s_%s_%s', ...
        CAL.cal_o_AgStructVersNr_u32, ...
        CAL.cal_o_AgActGrpNr_u32, ...
        cpc_cds_def(EEP.ptconf_p_Veh.VehClass_u8, 'VehClass'), ...
        cpc_cds_def(EEP.ptconf_a_Eng.EngType_u8, 'EngType'), ...
        cpc_cds_def(EEP.ptconf_a_Eng.CombustionClass_u8, 'CombustionClass'), ...
        cpc_cds_def(EEP.ptconf_p_Trans.TransType_u8, 'TransType'), ...
        cpc_cds_def(EEP.ptconf_p_Ret.RetType_u8, 'RetType'), ...
        cpc_cds_def(EEP.ag_p_VehConf.SftPrgAv_u8(1), 'SftProg'), ... % could be also CAL.cal_g_AgSftPrg_u8, but this parameter needs to be set properly (already happened with one NAFTA CDS, that it was not set properly)
        cpc_cds_def(EEP.ptconf_p_Veh.CustomType_u8, 'CustType') ...
        );
end


