function uiclassictabdemo
% UICLASSICTABDEMO demo function for GUI funtionality of uiclassictab
%
% Syntax:
%   uiclassictabdemo
%
% Inputs:
%
% Outputs:
%
% Example: 
%   uiclassictabdemo
%
%
% Subfunctions: gof, guiupdatetest, mpx_GUI_main_uimenu
%
% See also: uiclassictab
%
% Author: Rainer Frey, TP/EAF, Daimler Truck AG
%  Phone: +49-711-17-34246
% MailTo: rainer.r.frey@daimler.com
%   Date: 2019-06-24

% Initializing window for classic tab test
data.h0 = figure ('Units','pixel',...
   'Position',[45 60 950 640],...
   'NumberTitle','off',...
   'MenuBar','none',...
   'DockControls','off',...
   'Name','Classic tab test',...
   'Tag','test_classic_tab');

data = mpx_GUI_main_uimenu(data);

% uiclassictab - returns cell array of handles of panels (length = tabs)
data.p1 = uiclassictab('Parent',data.h0,...
   'Units','normalized',...
   'Position',[0.02 0.22 0.6 0.75],...
   'Foregroundcolor',[0 0 0],...
   'Backgroundcolor',[0.8 0.8 0.8],...
   'Shadowcolor',[0.3 0.3 0.3],...
   'String',{'Variables','Problem','Solver','Solutions'},...
   'type','left',...
   'FontSize',10,...
   'GuiUpdateFcn',{[],@guiupdatetest,[],[]});

% uiclassictab - returns cell array of handles of panels (length = tabs)
data.p2 = uiclassictab('Parent',data.p1{3},...
   'Units','normalized',...
   'Position',[0.02 0.22 0.6 0.75],...
   'Foregroundcolor',[0 0 0],...
   'Backgroundcolor',[0.8 0.8 0.8],...
   'Shadowcolor',[0.3 0.3 0.3],...
   'String',{'Var','Res'},...
   'type','left',...
   'FontSize',10);

% df = uicontrol('Parent',h0,...
%    'Units','normalized',...
%    'Position',[0.2 0.6 0.4 0.2],...
%    'Style','text',...
%    'FontName','Arial',...
%    'FontWeight','bold',...
%    'FontAngle','italic',...
%    'FontSize',10,...
%    'Backgroundcolor',[0.9 0.9 0.9],...
%    'String','GOLEM');
% 
% data.handles.main.b = uicontrol('Parent',h0,...
%    'Units','normalized',...
%    'Position',[0.01 0.01 0.4 0.24],...
%    'Callback',@bla,...
%    'Style','pushbutton',...
%    'FontName','Arial',...
%    'FontWeight','bold',...
%    'FontSize',9',...
%    'String','toggle');
% 

data.pu1 = uipanel('Parent',data.p1{1},...
       'Units','normalized',...
   'Backgroundcolor',[0.8 0.8 0.8],...
       'Position',[0.1 0.1 0.8 0.8]);
   
t1 = uicontrol('Parent',data.pu1,...
   'Units','normalized',...
   'Position',[0.01 0.01 0.4 0.24],...
   'Style','pushbutton',...
   'FontName','Arial',...
   'Backgroundcolor',[0.8 0.8 0.1],...
   'FontWeight','bold',...
   'FontSize',9',...
   'String','toggle1');

data.pu2 = uipanel('Parent',data.p1{2},...
       'Units','normalized',...
   'Backgroundcolor',[0.8 0.8 0.8],...
       'Position',[0.1 0.1 0.8 0.7]);
data.t1 = uicontrol('Parent',data.pu2,...
   'Units','normalized',...
   'Position',[0.01 0.01 0.4 0.24],...
   'Style','pushbutton',...
   'FontName','Arial',...
   'Backgroundcolor',[0.8 0.8 0.3],...
   'FontWeight','bold',...
   'FontSize',9',...
   'String','toggle2');

t1 = uicontrol('Parent',data.p2{2},...
   'Units','normalized',...
   'Position',[0.01 0.01 0.4 0.24],...
   'Style','pushbutton',...
   'FontName','Arial',...
   'Backgroundcolor',[0.8 0.8 0.1],...
   'FontWeight','bold',...
   'FontSize',9',...
   'Tag','toggle5',...
   'String','toggle5');

t1 = uicontrol('Parent',data.p2{1},...
   'Units','normalized',...
   'Position',[0.31 0.01 0.4 0.24],...
   'Style','pushbutton',...
   'FontName','Arial',...
   'Backgroundcolor',[0.8 0.8 0.1],...
   'FontWeight','bold',...
   'FontSize',9',...
   'Tag','toggle6',...
   'String','toggle6');


guidata(data.h0,data);

return


function data = mpx_GUI_main_uimenu(data)

% menu of main GUI
data.uim{1} = uimenu('Label','File');
         uimenu(data.uim{1},...
             'Label','New Source',...
             'Accelerator','N');
         uimenu(data.uim{1},...
             'Label','New Subset',...
             'Accelerator','M');
         uimenu(data.uim{1},...
             'Label','Load',...
             'Callback',@mpx_cb_load,...
             'Accelerator','L');
         uimenu(data.uim{1},...
             'Label','Save Source',...
             'Separator','on');
         uimenu(data.uim{1},...
             'Label','Save Subset');
         uimenu(data.uim{1},...
             'Label','Save All',...
             'Accelerator','S');
         uimenu(data.uim{1},...
             'Label','Close',...
             'Accelerator','Q',...
             'Separator','on');
data.uim{2} = uimenu('Label','Edit');
         uimenu(data.uim{2},...
             'Label','Classify Data');
         uimenu(data.uim{2},...
             'Label','Modify Data');
         uimenu(data.uim{2},...
             'Label','Modify Data');
data.uim{3} = uimenu('Label','Plot');
         uimenu(data.uim{3},...
             'Label','Create new Standard-Plot');
         uimenu(data.uim{3},...
             'Label','Create new ScrollPlot');
data.uim{4} = uimenu('Label','Help');
         uimenu(data.uim{4},...
             'Label','Help');
         uimenu(data.uim{4},...
             'Label','About');

return

function guiupdatetest(varargin)
[gcbuic,gcbf]=gcbo;
data = guidata(gcbf);
test = 1
set(data.t1,'Visible','off','String','t3')
return


function [object_handle,figure_handle] = gof(object_handle)
% figure_handle returns the figure of an object like uicontrol identified
% by the object handle
figure_handle = object_handle;
while ~strcmp(get(figure_handle,'Type'),'figure')
    figure_handle = get(figure_handle,'Parent');
end
return