nlInitParDef = [nlInitParDef; ...
	];

nlGlobalParDef.src = [nlGlobalParDef.src;...
    {'sMPG.rcm_x_ret_GW_rpm','sMP.ctrl.tcm.x_ret_GW_rpm'};...
    {'sMPG.rcm_y_ret_M_max','sMP.ctrl.tcm.y_ret_M_max'}...
    ];
nlGlobalParDef.dest = [nlGlobalParDef.dest;...
    {'sMPG.rcm_x_ret_GW_rpm','sMP.ctrl.tcm.x_ret_GW_rpm'};...
    {'sMPG.rcm_y_ret_M_max','sMP.ctrl.tcm.y_ret_M_max'};...
    {'sMPG.axleiDiff','sMP.ctrl.tcm.axleiDiff'};...
    {'sMPG.mcm_idleSpeed_rpm','sMP.ctrl.tcm.eng_idleSpeed'};...
    {'sMPG.m_kg','sMP.ctrl.tcm.mVeh'};...
    {'sMPG.osg_eng_speed_max_1m','sMP.ctrl.tcm.eng_maxSpeed'};...
    {'sMPG.wheelf_R','sMP.ctrl.tcm.fRFzg'};...
    {'sMPG.wheelR_d','sMP.ctrl.tcm.rDyn'};...
    {'sMPG.tbf_trq_max_r0_2m','sMP.ctrl.tcm.eng_maxTorque'};...
    {'sMPG.airDensity_kgpm3','sMP.ctrl.tcm.rhoAir'}...
    ];