% -------------------------------------------------------------------------
% CPC5_SFUN_InitFcn.m - generated by Silver T-2022.03-4
% Copyright QTronic GmbH. All rights reserved.
% -------------------------------------------------------------------------

% This m script is loaded when running CPC5_SFUN_wrapper.mdl, because in Simulink
%   File/ModelProperties/Callbacks/InitFcn = CPC5_SFUN_InitFcn
% Edit this file to change parameter values passed to CPC5_SFUN.mexw32

% user_config = '-j 0.1 -W 4 -X 0 -Y TCP -Z 5555'; % user_config options concatenated in one string.
% -a	: Parameter File; required: yes; default: 0;
% -b	: Init Value File; required: yes; default: 0;
% -c	: Par Default File; required: yes; default: 0;
% -d	: Calibration Data Set; required: yes; default: 0;
% -e	: CDStxtFileOutput; required: yes; default: 0;
% -f	: Names of signals to save after simulation; required: yes; default: 0;
% -g	: Target file to save signals after simulation; required: yes; default: 0;
% -h	: Debugging Output File; required: yes; default: 0;
% -i	: Debugging Definition File; required: yes; default: 0;
% -j	: Debugging Step Size; required: yes; default: 0;
% -W	: log level (default: INFO); required: yes; default: INFO;
% -X	: xcp enabled (default: 0); required: yes; default: off;
% -Y	: xcp protocol (default: TCP); required: yes; default: TCP;
% -Z	: xcp ipPort (default: 5555); required: yes; default: 0;;
