function [sClient,nStatus] = p4client(sClient,sStream,sRoot,sDescription,varargin)
% P4CLIENT create a Perforce Helix client/workspace from the specified
% stream at the defined location. The arguments for client name, stream,
% client root location and description are explicit. All other arguments
% can accessed via parameter/value pairs as optional arguments.
% Default settings:
% SubmitOptions = revertunchanged
% LineEnd = local
% Options = allwrite noclobber compress unlocked modtime rmdir
%
% Syntax:
%   sClient = p4client(sClient,sStream,sRoot)
%   sClient = p4client(sClient,sStream,sRoot,sDescription,sType)
%   [sClient,nStatus] = p4client(sClient,sStream,sRoot,sDescription,varargin)
%
% Inputs:
%   sClient - string with client name (if empty standard format is used)
%   sStream - string with stream as depot notation (e.g. //DIVe/d_main)
%     sRoot - string with root folder path for workspace (files go here)
%   sDescription - string with description
%     varargin - [optional] Parameter/value pairs of further options, see
%                parseArgs input for details
%
% Outputs:
%   sClient - string with used workspace
%   nStatus - integer (1x1) with exit code (0:success,1:failure)
%
% Example: 
%   sClient = p4client('','//DIVe/drd_DIVeScripts','C:\temp\exampleExport')
%   sClient = p4client('','//DIVe/drd_DIVeScripts','C:\temp\exampleExport','Some new client')
%   sClient = p4client('','//DIVe/drd_DIVeScripts','C:\temp\exampleExport','','Allwrite','noallwrite')
%   sClient = p4client('','//DIVe/drd_DIVeScripts','/home/rafrey5/08Helix/drd_DIVeScripts','Linux test workspace',...
%       'Allwrite','noallwrite','Clobber','noclobber','Compress','compress','Modtime','modtime','Rmdir','rmdir','SubmitOptions','revertunchanged')
%
% See also: p4form, strGlue, strsplitOwn
%
% Author: Rainer Frey, TP/EAD, Daimler AG
%  Phone: +49-711-17-34246
% MailTo: rainer.r.frey@daimler.com
%   Date: 2018-10-25

% input check
[xArg,cRest] = parseArgs({'Type','writeable',[];
                          'Allwrite','allwrite',[];
                          'Clobber','noclobber',[];
                          'Compress','compress',[];
                          'Locked','unlocked',[];
                          'Modtime','modtime',[];
                          'Rmdir','rmdir',[];
                          'SubmitOptions','revertunchanged',[];
                          'LineEnd','local',[]},...
                          varargin{:});
if ~isempty(cRest)
    fprintf(2,['p4client argument parsing could not address the following ' ...
               'arguments: %s\n'],strGlue(cRest,', '));
end

% input check
if nargin < 4
    sDescription = 'Client generated by p4client.';
end

% default client name
cStream = strsplitOwn(sStream,'/',true);
[sUser,sHost] = getenvOwn({'username','computername'});
if isempty(sClient)
    sClient = strGlue({lower(sUser),sHost,cStream{end}},'_');
end

% ensure existence of client/workspace path
if ~exist(sRoot,'dir')
    mkdir(sRoot);
end

% create Client
[nStatus,sMsg] = p4form('client',...
                        'Client',{sClient},...
                        'Description',{sDescription},...
                        'Root',{sRoot},...
                        'Stream',{sStream},...
                        'SubmitOptions',{xArg.SubmitOptions},...
                        'Type',{xArg.Type},...
                        'LineEnd',{xArg.LineEnd},...
                        'Options',{['"' strGlue({xArg.Allwrite, ...
                                                 xArg.Clobber, ...
                                                 xArg.Compress, ...
                                                 xArg.Locked, ...
                                                 xArg.Modtime, ...
                                                 xArg.Rmdir},' ') '"']});
if nStatus
    % failure of p4 command
    fprintf(2,'p4client failure with message:\n%s\n',sMsg);
end
return
