function [extraDataMain,extraDataInit] = extraData()
% EXTRADATA <one line description>
% <Optional file header info (to give more details about the function than in the H1 line)>
%
% Syntax:
%   [extraDataMain,extraDataInit] = extraData
%
% Inputs:
%
% Outputs:
%   extraDataMain - 
%   extraDataInit - 
%
% Example: 
%   [extraDataMain,extraDataInit] = extraData
%
%
% Subfunctions:
% Private functions:
% Other m-files required:
% MAT-files required:
%
% See also: dcmRead
%
% Author: Andre Overfeld, TP/EAD, Daimler AG
%  Phone: +49-711-17-26049
% MailTo: andre.overfeld@daimler.com
%   Date: 2017-08-25

extraDataMain = {...
    'osg_eng_speed_max_1m';...
    'osg_eng_speed_max_r0_1m';...
    'tbf_trq_max_r0_x_eng_speed';...
    'tbf_trq_max_r1_x_eng_speed';...
    'tbf_trq_max_r2_x_eng_speed';...
    'tbf_trq_max_r0_2m';...
    'tbf_trq_max_r2_2m';...
    'tbf_trq_max_r1_2m';...
    'tbf_trq_max_r0_eng_speed_idx_cpc_1m';...
    'tbf_trq_max_r1_eng_speed_idx_cpc_1m';...
    'tbf_trq_max_r2_eng_speed_idx_cpc_1m';...
    'sys_can_performance_class_1m';...
    'cac_br_trq_ebs_x_rpm';...
    'cac_br_trq_ebs1_min_2m';...
    'cac_br_trq_ebs2_min_2m';...
    'cac_br_trq_ebs3_min_2m';...
    'ebm_ebs1_temp_speed_cond_off_2m';...
    'ebm_ebs1_temp_speed_cond_on_2m';...
    'ebm_ebs1_temp_speed_cond_x_speed';...
    'ebm_ebs2_temp_speed_cond_off_2m';...
    'ebm_ebs2_temp_speed_cond_on_2m';...
    'ebm_ebs2_temp_speed_cond_x_speed';...
    'epf_ebm_overspeed_1m';...
    'epf_warn_overspeed_1m';...
    'osg_eng_speed_max_ext_1m';...
    'osg_trq_red_fac_2m';...
    'osg_trq_red_fac_x_over_speed';...
    'sys_can_engine_char_1m';...
    'sys_can_trq_inertia_1m';...
    'sys_cylinder_value_1m';...
    'tfc_fm_tm_x_eng_speed';...
    'tfc_fm_tm_y_trq';...
    'tfc_fm_tmh_3m';...
    'tic_trq_loss_fric_3m';...
    'tic_trq_loss_fric_x_eng_speed';...
    'tic_trq_loss_fric_y_t_eng_oil';...
    'sys_eng_brk_perf_by_e2p_1m';...
    'cac_br_trq_ebs1_max_std_2m';...
    'cac_br_trq_ebs2_max_std_2m';...
    'cac_br_trq_ebs3_max_std_2m';...
    'cac_br_trq_ebs1_max_2m';...
    'cac_br_trq_ebs2_max_2m';...
    'cac_br_trq_ebs3_max_2m';...
    'lig_eng_speed_des_2m';...
    'cac_br_trq_ebs_x_rpm';...
    'sys_motor_type_1m';...
    'sys_can_eng_brk_performance_1m';...
    'etc_fac_dur_post2_1m';...
	'sys_max_trq_speed_1m';...
	'sys_max_eng_trq_1m';...
	'sys_can_speed_power_rating_1m'...
    };

extraDataInit = {...
    'par_table.par_basic.e2p_sys_engine_brake_variant'...
	};

% Parameters = readDCMParameters('X_M121103_CBN612LF195_prelim01.dcm',parameterList);
% Parameters = dcmRead('X_M121103_CBN612LF195_prelim01.dcm',parameterList);