function [varargout] = getErrPtcEepDatPos(n)

defintion = {
0, 'PTConf parameter set o.k.'
1, 'ptconf_p_Trans.GearRatio_s16'
2, 'ptconf_p_Trans.ForwGearNum_u8'
3, 'ptconf_p_Trans.RevGearNum_u8'
4, 'ptconf_p_TransCase.TransCaseGearRatio_u16'
5, 'ptconf_p_TransCase.TransCaseGearNum_u8'
6, 'ptconf_p_Trans.TransWrkGrpWrkRatio_u16'
7, 'ptconf_p_Trans.TransCrawlGrpCrawlRatio_u16'
8, 'ptconf_p_Trans.TransType_u8'
9, 'ptconf_p_Veh.VehClass_u8'
10, 'ptconf_p_Veh.VehType_u8'
11, 'ptconf_p_AxleFront.AxleRatio_u16 and ptconf_p_AxleRear.AxleRatio_u16'
12, 'ptconf_p_Ret.RetType_u8'
13, 'ptconf_p_Veh.VehFrontArea_u16'
14, 'ptconf_p_Veh.VehDragCoeff_u8'
15, 'ptconf_p_Trans.GearFricEff_u8'
16, 'ptconf_p_TransCase.TransCaseFricGearEff_u8'
17, 'ptconf_p_AxleFront.AxleFricEff_u8 and ptconf_p_AxleRear.AxleFricEff_u8'
18, 'ptconf_p_Tire.TireRollResCoeff_u8'
19, 'ptconf_p_Trans.TransWrkGrpWrkFricEff_u8'
20, 'ptconf_p_Trans.TransCrawlGrpCrawlFricEff_u8'
21, 'ptconf_p_Veh.NumOfDrvWheels_u8'
22, 'ptconf_p_Veh.NumOfAllWheels_u8'
23, 'ptconf_p_Tire.NumOfTiresPerRearSusp_u8'
24, 'ptconf_p_Veh.MinVehMass_u16'
25, 'ptconf_p_Veh.MaxVehMass_u16'
26, 'ptconf_p_Clutch.ClutchInertiaTrqPri_u16'
27, 'ptconf_p_Clutch.ClutchInertiaTrqSec_u16'
28, 'ptconf_p_Trans.TransInertiaTrq_u16'
29, 'ptconf_p_Ret.PriRetPriSideInertiaTrq_u16'
30, 'ptconf_p_Ret.PriRetSecSideInertiaTrq_u16'
31, 'ptconf_p_Ret.SecRetInertiaTrq_u16'
32, 'ptconf_p_TransCase.TransCasePlanRatio_u16'
33, 'ptconf_p_AxleRear.AxleRatio1_u16'
34, 'ptconf_p_AxleRear.AxleRatio2_u16'
35, 'ptconf_p_Tire.MinDynWheelRad_u16'
36, 'ptconf_p_Tire.MaxDynWheelRad_u16'
37, 'ptconf_p_AxleFront.HlfShftStff_u16 / ptconf_p_AxleRear.HlfShftStff_u16'
38, 'ptconf_p_Trans.TransStff_u16'
39, 'ptconf_p_Clutch.ClutchStff_u16'
40, 'ptconf_p_Tire.RotTireStff_u16'
41, 'ptconf_p_DrvShft.DrvShftStff_u16'
42, 'ptconf_p_AxleFront.AxleType_u8 and ptconf_p_AxleRear.AxleType_u8'
43, 'ptconf_p_Clutch.ClutchType_u8'
44, 'ptconf_p_TransCase.TransCaseType_u8'
45, 'ptconf_p_Veh.FlcSelPar_u8'
46, 'ptconf_p_Ret.AllisonSpdsSampleDelta_u8'
47, 'ptconf_p_Tire.DrvWheelInertiaTrq_u16'
48, 'ptconf_p_Tire.NonDrvWheelInertiaTrq_u16'
49, 'ptconf_p_Tire.TrlWheelInertiaTrq_u16'
50, 'ptconf_p_Tire.NumOfTrlWheels_u8'
51, 'ptconf_p_PTO.NMVVar_u8'
52, 'ptconf_p_PTO.NMVRatio_u16'
53, 'ptconf_p_PTO.CountShaftPTONum_u8'
54, 'ptconf_p_PTO.EngPTOType_u8'
55, 'ptconf_p_Ret.PMRSteadyStateFact_u8'
56, 'ptconf_p_Ret.PMRTimeConst_u8'
57, 'ptconf_p_Clutch.ClutchAutLvl_u8'
58, 'ptconf_p_Ret.TrbTransRatio_u16'
59, 'ptconf_p_Veh.FlcManPar_u8'
60, 'ptconf_p_Veh.PriSpdSel_u8'
61, 'ptconf_p_Veh.FlcReqActv_u8'
62, 'ptconf_p_Veh.NumOfFrontDrvWheels_u8'
100, 'ptconf_a_EngBrk.EngBrkStp1TrqCrvEngSpds_u8'
101, 'ptconf_a_EngBrk.EngBrkStp1MinBrkTrqs_u16'
102, 'ptconf_a_EngBrk.EngBrkStp1MaxBrkTrqs_u16'
103, 'ptconf_a_EngBrk.EngBrkStp2TrqCrvEngSpds_u8'
104, 'ptconf_a_EngBrk.EngBrkStp2MinBrkTrqs_u16'
105, 'ptconf_a_EngBrk.EngBrkStp2MaxBrkTrqs_u16'
106, 'ptconf_a_EngBrk.EngBrkStp3TrqCrvEngSpds_u8'
107, 'ptconf_a_EngBrk.EngBrkStp3MinBrkTrqs_u16'
108, 'ptconf_a_EngBrk.EngBrkStp3MaxBrkTrqs_u16'
109, 'ptconf_a_Eng.EngType_u8'
110, 'ptconf_a_Eng.CombustionClass_u8'
111, 'ptconf_a_Eng.MaxPermEngBrkSpd_u16'
112, 'ptconf_a_Eng.WarnBuzzEngSpd_u16'
113, 'ptconf_a_Eng.MaxEngSpdGov0EngSpd_u16'
114, 'ptconf_a_Eng.EngInertiaTrq_u16'
115, 'ptconf_a_Eng.FullLoadEngTrqCurvesEngSpds_u16'
116, 'ptconf_a_Eng.TrbChFullLoadEngTrqCurve_u16'
117, 'ptconf_a_Eng.UnChFullLoadEngTrqCurve_u16'
118, 'ptconf_a_Eng.EngDerateSpdInt_u16'
119, 'ptconf_a_EngFric.EngFricTrqMapTrq_u16'
120, 'ptconf_a_EngFric.EngFricTrqMapEngSpd_u8'
121, 'ptconf_a_EngFric.EngFricTrqMapTemp_u8'
122, 'ptconf_p_Ret.RetMaxBrkTrqs_u16'
123, 'ptconf_a_EngConsum.EngConsumMapEngSpds_u8'
124, 'ptconf_a_EngConsum.EngConsumMapEngTrqs_u8'
125, 'ptconf_a_EngConsum.EngConsumMapFuelMass_u16'
126, 'ptconf_a_Eng.MinEngBrkSpd_u16'
127, 'ptconf_a_Eng.MaxEngBrkSpd_u16'
128, 'ptconf_a_Eng.EngBrkVar_u8'
129, 'ptconf_a_Eng.TopTrqRedFullLoadEngTrqCurve_u16'
130, 'ptconf_a_Eng.TopTrqRedEngTrqCurveEngSpds_u16'
131, 'ptconf_a_Eng.TopTrqRedEngDerateSpdInt_u16'
132, 'ptconf_a_Eng.J1939EngInertiaTrq_u16'
133, 'ptconf_p_Trans.SftPrgCode_u8'
134, 'ptconf_p_Veh.ThermoRollEn_u8'
};

if n == 0
    s = sprintf('PTConf parameter set o.k.');
else 
    idx = [defintion{:,1}] == n;
    s = sprintf('error signal %s', defintion{idx,2});
end

% Output in Command window
if nargout == 0
    fprintf('%s\n', s);
else
    varargout{1} = s;
end
